name: 'Cache reference build from merged commit on develop'
on:
  push:
    branches:
      - 'develop'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        path: codedir

    - name: cache-spack
      uses: actions/cache/restore@v4
      with:
        path: ${{ github.workspace }}/spack-develop
        key: spack-${{ hashFiles('codedir/ci/spack.yaml') }}-gcc12-mpich

    - name: setup
      shell: bash
      run: |
        . ${GITHUB_WORKSPACE}/spack-develop/share/spack/setup-env.sh
        spack env activate gcc12
        spack load $(spack find --format "{name}")
        env >> $GITHUB_ENV
        cd ${GITHUB_WORKSPACE}/codedir
        git clone https://github.com/NOAA-EMC/CMakeModules
        git clone --recurse-submodules https://github.com/NOAA-PSL/stochastic_physics stochastic_physics_repo
        echo "we are here"

    - name: Generate reference build
      uses: AlexanderRichert-NOAA/ci-cache-cmake-build/cache-reference-build@main
      with:
        source-dir: codedir
        build-dir: build
        config-args: -D32BIT=ON
