name: 'Cache reference build from merged commit on develop'
on:
  push:
    branches:
      - 'develop'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        path: codedir

    - name: Generate reference build
      uses: AlexanderRichert-NOAA/ci-cache-cmake-build/cache-reference-build@main
      with:
        source-dir: codedir
        build-dir: build
        config-args: -D32BIT=ON
